[[redirects]] 
  from = "/*" 
  to = "/laina.html" 
  status = 200

[build]
  command = "cd functions/render/ && npm install && cd ../../ && npm run build"
  publish = "build/"
  functions = "functions/"